# PX4 Controller Debug Information
Header header

# Error in axis angle
float64 err_axisang_x
float64 err_axisang_y
float64 err_axisang_z

# Desired velocity
float64 des_v_x
float64 des_v_y
float64 des_v_z

# Feedback attitude (in degrees)
float64 fb_a_x
float64 fb_a_y
float64 fb_a_z

# Desired acceleration
float64 des_a_x
float64 des_a_y
float64 des_a_z

# Desired quaternion
float64 des_q_x
float64 des_q_y
float64 des_q_z
float64 des_q_w

# Feedback rate
float64 fb_rate_x
float64 fb_rate_y
float64 fb_rate_z

# Desired thrust
float64 des_thr

# Timestamps
time des_time
time real_time 